"""add deadline to course

Revision ID: 5b8d93512530
Revises: 7c363ff52dd4
Create Date: 2026-07-17 14:18:58.350302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8d93512530'
down_revision: Union[str, None] = '7c363ff52dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'deadline')
    # ### end Alembic commands ###
